In [1]:
"""
Environment (Ortam)
Agent(Ajan) : İnsan Ajan, Robotic Ajan, Yazılım Ajanı
"""

'\nEnvironment (Ortam)\nAgent(Ajan) : İnsan Ajan, Robotic Ajan, Yazılım Ajanı\n'

In [2]:
#Single Layer Perceptron (Tensorflow versiyonu)
import warnings
warnings.filterwarnings('ignore')

In [3]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data", one_hot = True)

ModuleNotFoundError: No module named 'tensorflow.examples'

In [4]:
"""
red green blue
1    0     0
0    1     0
0    0     1
"""

'\nred green blue\n1    0     0\n0    1     0\n0    0     1\n'

In [5]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']

values = array(data)
print(values)

#integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]


In [7]:
#binary encode 
onehot_encoder = OneHotEncoder(sparse = False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [8]:
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['cold']


In [18]:
import tensorflow as tf
import matplotlib.pyplot as plt

In [19]:
learning_rate = 0.01
training_epochs = 25
batch_size = 100
display_step = 1

In [24]:
x = tf.placeholder('float', [None, 784])
y = tf.placeholder('float', [None, 10])

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [25]:
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

activation = tf.nn.softmax(tf.matmul(x, W) + b)

cross_entropy = y*tf.log(activation)
cost = tf.reduce_mean(-tf.reduce_sum(cross_entropy, reduction_indices = 1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

avg_set = []
epoch_set = []

init = tf.initialize_all_variables()
with tf.Session() as sess:
    sess.rung(init)
    
    #Eğitim Döngüleri
    for epoch in range(training_epochs):
        avg_cost = 0
        total_batch = int(mnist.train.num_examples / batch_size)
        
        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            
            sess.run(optimizer, feed_dict = {x: batch_xs, y: batch_ys})
            
            avg_cost += sess.run(cost,feed_dict = {x: batch_xs, y: batch_ys}) / total_batch)
        if epoch % display_step == 0:
            print('Epoch:','%04d' % (epoch + 1), 'cost=', '{:.9f}'.format(avg_cost))
        avg_set.append(avg_cost)
        apoch_set.append(epoch + 1)
    print('Training fazı tamamlandı')
    plt.plot(epoch_set, avg_set, 'o', label = 'Training Fazı')
    plt.ylabel('cost')
    plt.xlabel('epoch')
    plt.legend()
    plt.show()
    
    dogru_tahmin = tf.equal(tf.argmax(activation, 1), tf.argmax(y, 1))
    accuracy = tf.reduce_mean(tf.cast(dogru_tahmin, 'float'))
    print('Model accuracy: ', accuracy.eval({x : mnist.test.images, y : mnist.test.labels}))

NameError: name 'x' is not defined

In [26]:
#Multilayer perceptron
learning_rate = 0.001
training_epochs = 20
batch_size = 100
display_step = 1

In [27]:
n_input = 784
n_classes = 10
n_hidden_1 = 256
n_hidden_2 = 256

In [ ]:
x = tf.placeholder('float', [None, n_input])
y = tf.placeholder('float', [None, n_classes])

In [ ]:
#Katman 1 için ağırlıklar
h = tf.Variable(tf.random_normal([n_input, n_hidden_1]))
#Katman 1 için bias
bias_layer_1 = tf.Variable(tf.random_normal([n_hidden_1])
#Katman 1
layer_1 = tf.nn.sigmoid(tf.add(tf.matmul(x, h), bias_layer_1))
                           
#Katman 2 için ağırlıklar
w = tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2]))
#Katman 2 için bias
bias_layer_2 = tf.Variable(tf.random_normal([n_hidden_2]))
#Katman 2
layer_2 = tf.nn.sigmoid(tf.add(tf.matmul(layer_1, w), bias_layer_2))
                           
#Output Katmanı tüm denklemler
output = tf.Variable(tf.random_normal([n_hidden_2, n_classes]))
bias_output = tf.Variable(tf.random_normal([n_classes]))
output_layer = tf.matmul(layer_2, output) + bias_output
                           
cost = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits = output_layer, labels = y))
optimizer = tf.train.AdamOptimizer(learning_rate = learning_rate).minimize(cost)     
 
avg_set = []
epoch_set = []

init = tf.initialize_all_variables()
with tf.Session() as sess:
    sess.rung(init)
    
    #Eğitim Döngüleri
    for epoch in range(training_epochs):
        avg_cost = 0
        total_batch = int(mnist.train.num_examples / batch_size)
        
        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            
            sess.run(optimizer, feed_dict = {x: batch_xs, y: batch_ys})
            
            avg_cost += sess.run(cost,feed_dict = {x: batch_xs, y: batch_ys}) / total_batch)
        if epoch % display_step == 0:
            print('Epoch:','%04d' % (epoch + 1), 'cost=', '{:.9f}'.format(avg_cost))
        avg_set.append(avg_cost)
        apoch_set.append(epoch + 1)
    print('Training fazı tamamlandı')
    plt.plot(epoch_set, avg_set, 'o', label = 'Training Fazı')
    plt.ylabel('cost')
    plt.xlabel('epoch')
    plt.legend()
    plt.show()
    
    dogru_tahmin_2 = tf.equal(tf.argmax(output_layer, 1), tf.argmax(y, 1))
    accuracy = tf.reduce_mean(tf.cast(dogru_tahmin_2, 'float'))
    print('Model accuracy (MLP): ', accuracy.eval({x : mnist.test.images, y : mnist.test.labels}))                           