In [3]:
from numpy import *
import time

In [2]:
def trad_version():
    t1 = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
        
    return time.time() - t1

trad_version()


3.5269992351531982

In [3]:
def numpy_version():
    
    t1 = time.time()
    X = arange(10000000)
    Y = arange(10000000)
    Z = X + Y
    
    return time.time() - t1

numpy_version()

0.04295158386230469

In [5]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")


In [5]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [7]:
type(list1)

list

In [10]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [11]:
type(arr1)

numpy.ndarray

In [12]:
arr1.data

In [13]:
arr1.dtype

dtype('int32')

In [14]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
np.arange(100,10,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [20]:
arr3 = np.arange(0,10)
arr3.shape

(10,)

In [21]:
arr3.size

10

In [22]:
arr3.itemsize

4

In [23]:
arr3.dtype

dtype('int32')

In [24]:
arr3.nbytes

40

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [15]:
a = np.array([10,20,30])
np.repeat(a,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [29]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [31]:
ar1 = np.arange(1,20)
ar1[ar1 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [33]:
ar1 = np.arange(1,20)
ar1[ar1 % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [37]:
  np.random.random(4)

array([0.54955509, 0.10910526, 0.67671114, 0.68768051])

In [38]:
np.random.randint(0,500,5)

array([296, 339, 322, 370, 115])

In [41]:
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [42]:
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [43]:
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [45]:
f1 = np.random.uniform(5, 10, size = (10))
f1

array([6.5348311 , 9.4680654 , 8.60771931, 5.94969477, 7.77113796,
       6.76065977, 5.90946201, 8.92800881, 9.82741611, 6.16176831])

In [46]:
np.floor(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [47]:
f1.astype(int)

array([6, 9, 8, 5, 7, 6, 5, 8, 9, 6])

In [48]:
b2 = np.random.randn(10)
b2

array([ 0.18869531, -0.75887206, -0.93323722,  0.95505651,  0.19079432,
        1.97875732,  2.60596728,  0.68350889,  0.30266545,  1.69372293])

In [49]:
arr1

array([10, 20, 30, 40, 50, 60])

In [51]:
for index, value in np.ndenumerate(arr1):
    print(index,value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [53]:
arr2 = np.arange(1,20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [54]:
arr2.sum()

190

In [55]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [56]:
# min(), max(), argmin(), argmax(), mean(), median(), var()

In [57]:
np.std(arr2)

5.477225575051661

In [60]:
a = np.array([[1,2,3,0],[5,6,7,22],[5,23,14,55]])
a

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [ 5, 23, 14, 55]])

In [61]:
a.sum()

143

In [63]:
a.min()

0

In [64]:
a.max()

55

In [66]:
np.amin(a, axis = 0)

array([1, 2, 3, 0])

In [67]:
np.amin(a, axis = 1)

array([0, 5, 5])

In [68]:
for index, value in np.ndenumerate(a):
    print(index,value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 5
(2, 1) 23
(2, 2) 14
(2, 3) 55


In [69]:
a = np.array([7,5,3,9,0,2])
a[0]

7

In [70]:
a[1:]

array([5, 3, 9, 0, 2])

In [71]:
a[1:4]

array([5, 3, 9])

In [72]:
a[-1]

2

In [74]:
a[-3:-1]

array([9, 0])

In [76]:
ar = np.arange(1,20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [78]:
rep1 = np.where(ar % 2 == 0, 0, ar)
rep1

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19])

In [79]:
ar2 = np.array([10,20,30,10,10,20,20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [82]:
rep2 = np.where(ar2 == 10, 99, ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [83]:
p2 = np.arange(0,100,10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [84]:
np.put(p2, [0,3,5], [33,55,99])
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])

In [85]:
a = np.array([10, np.nan, 20, 30, 60, np.nan, 90, np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [86]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [87]:
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [90]:
a[np.isnan(a)] = 66
a

array([10., 66., 20., 30., 60., 66., 90., inf])

In [91]:
np.isnan(a).any()

False

In [92]:
A = np.array([[2,6,np.nan,8],[np.nan,6,7,9],[2,np.nan,6,3],[15,12,4,11]])
A

array([[ 2.,  6., nan,  8.],
       [nan,  6.,  7.,  9.],
       [ 2., nan,  6.,  3.],
       [15., 12.,  4., 11.]])

In [94]:
np.isnan(A)

array([[False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [95]:
np.where(np.isnan(A))

(array([0, 1, 2], dtype=int64), array([2, 0, 1], dtype=int64))